"""Add returned and used to ShiftInventory

Revision ID: fb410c413f37
Revises: 
Create Date: 2025-07-14 11:20:28.307493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb410c413f37'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('main_data')
    with op.batch_alter_table('shift_inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('returned', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('used', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift_inventory', schema=None) as batch_op:
        batch_op.drop_column('used')
        batch_op.drop_column('returned')

    op.create_table('main_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('shift', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
    sa.Column('acknowledged', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('checkin', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='main_data_pkey')
    )
    # ### end Alembic commands ###
