version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: p3checkuser
      POSTGRES_PASSWORD: p3checkpass
      POSTGRES_DB: p3checklist
    ports:
      - "5432:5432"
    volumes:
      - p3checklist_data:/var/lib/postgresql/data
volumes:
  p3checklist_data: